name            = "ITC Land Systems v0.0.0";    // Name of your mod
author          = "ITC Addons Team";            // Affects Arma 3 Launcher, when the mod are loaded as local
logo            = "itc-combo.paa";              // Logo displayed in the main menu
logoOver        = "itc-combo.paa";              // When the mouse is over, in the main menu
tooltip         = "ITC Land Systems";
tooltipOwned    = "ITC Land Systems";           // Tool tip displayed when the mouse is left over, in the main menu
picture         = "itc-combo.paa";              // Picture displayed from the expansions menu. Optimal size is 2048x1024
actionName      = "GitHub";
action          = "https://github.com/Andx667/ITC_Land_Systems";    // Website URL, that can be accessed from the expansions menu
overview        = "Improvements to ArmA 3 Land Systems.";   // Supports structured text
hideName        = 0;                            // Hide the extension name
hidePicture     = 0;                            // Hide the extension menu
logoSmall       = "itc-combo.paa";              // Display in creative lists, next to the entities added by the mod
